#!/usr/bin/env bash
# This script displays the content of the current directory
# It shows only the part of the name after the first dash (-)
# Hidden files are not displayed

for file in *
do
    if [[ -e "$file" && "$file" != .* ]]
    then
        echo "$file" | cut -d '-' -f 2-
    fi
done
